name: 'S3 TO UNZIP'
description: 'Download and Unzip an Node Package from S3'
inputs:
  folder:  # folder name
    description: 'Folder Name'
    required: true
    default: 'production'
  aws_key_id:
    description: 'AWS Key ID'
    required: true
  aws_key:
    description: 'AWS Key'
    required: true
  aws_bucket:
    description: 'AWS Bucket'
    required: true
  addIgnore:
    description: 'Add Ignore?'
    required: true
    default: 'true'
  ignore:
    description: 'Ignore Files'
    required: true
    default: '/source\n/src\n/database\n'
runs:
  using: "composite"
  steps:
  - name: Download a package
    uses: Bhacaz/checkout-files@master
    with:
      files: package.json
      token: ${{ github.token }}
  - name: GET VERSION
    id: package-version
    uses: martinbeentjes/npm-get-version-action@master
  - name: Copy From S3
    uses: prewk/s3-cp-action@v2
    with:
      aws_access_key_id: ${{ inputs.aws_key_id }}
      aws_secret_access_key: ${{ inputs.aws_key }}
      source: s3://${{ inputs.aws_bucket }}/${{ github.event.repository.name }}/${{ inputs.folder }}/${{ steps.package-version.outputs.current-version }}.zip
      dest: ./
  - name: Add Ignore
    if: ${{ inputs.addIgnore == 'true' }}
    run: echo -e '${{ steps.package-version.outputs.current-version }}*\n${{ inputs.ignore }}' >> .npmignore
    shell: bash
  - name: Print
    run: ls
    shell: bash
  - name: Extract some files
    run: 7z x ${{ steps.package-version.outputs.current-version }}.zip -aoa
    shell: bash
  - name: Print end
    run: ls
    shell: bash

